name: cashjar_dart
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: ruslankharakhashyan <ruslankharakhashyan@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0
  firebase: ^5.0.4
  firebase_dart_ui: ^0.1.2
  angular_router: ^2.0.0-alpha+22
  grpc: ^2.1.1
  protobuf: ^0.13.6
  intl:
  js: ^0.6.0
  exifdart: ^0.7.0+3
  image: ^2.1.4

  cashjar_common:
    path: '../cashjar_common'

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.5.0
  build_test: ^0.10.3
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
  test: ^1.6.0
